---
- name: Deploy exporters to DNS servers
  hosts: dns_servers
  become: yes
  roles:
    - node_exporter
    - bind_exporter

- name: Deploy exporters to NTP server
  hosts: ntp_servers
  become: yes
  roles:
    - node_exporter
    - chrony_exporter

- name: Deploy exporters to DHCP server
  hosts: dhcp_servers
  become: yes
  roles:
    - node_exporter
